/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PassCheckDialog.java
 *
 * Created on 2010-7-24, 12:37:37
 */
package com.goldsign.fm.dialog;

import com.goldsign.fm.common.AppConstant;
import com.goldsign.fm.common.AppUtil;
import com.goldsign.fm.common.PubUtil;
import com.goldsign.fm.common.swing.LengthLimitDocument;
import com.goldsign.fm.dao.PassDao;
import com.goldsign.fm.vo.PassResult;
import java.awt.Frame;
import java.awt.HeadlessException;
import org.apache.log4j.Logger;

/**
 *
 * @author Administrator
 */
public class PassCheckDialog extends javax.swing.JDialog {
    private static Logger logger = Logger.getLogger(PassCheckDialog.class.getName());
    private PassResult checkResult;

    /** Creates new form PassCheckDialog */
    public PassCheckDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public PassCheckDialog(Frame owner,
            String title,
            boolean modal,PassResult checkResult)
            throws HeadlessException {
        super(owner, title, modal);
        initComponents();
        this.checkResult=checkResult;
        this.init();

    }

    private void init() {
        AppUtil.setIcon(this, "pass.jpg");
        this.jPasswordFieldPass.setDocument(new LengthLimitDocument(6, true, true));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPass = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelPass.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jLabelPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPass.setText("密码:");

        jButtonOk.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButtonOk.setText("确定");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jButtonOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonOkKeyPressed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButtonCancel.setText("取消");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jButtonCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButtonOk)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass)
                    .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.checkResult.setIsSuccess(false);
        this.dispose();

    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
          String pass = this.jPasswordFieldPass.getText().trim();

        if(!this.checkInput(pass))
             return;
         PassDao dao = new PassDao();
         PassResult ret ;
        try {
            ret =dao.checkPass(pass);
            if(ret.isIsSuccess())
            {
                this.dispose();
                this.checkResult.setIsSuccess(true);
                return;
            }
            else{
                PubUtil.prompt(this,ret.getMsg());
            }
        } catch (Exception ex) {
           
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonOkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonOkKeyPressed
        // TODO add your handling code here:
        jButtonOkActionPerformed(null);
    }//GEN-LAST:event_jButtonOkKeyPressed

    private void jButtonCancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelKeyPressed
        // TODO add your handling code here:
        this.jButtonCancelActionPerformed(null);
    }//GEN-LAST:event_jButtonCancelKeyPressed
    private boolean checkInput( String pass ){


        if(pass.length()==0){
            PubUtil.prompt(this,"密码不能为空");
            PubUtil.focus(jPasswordFieldPass);
            
            return false;
        }
        if(pass.length()!=6){
            PubUtil.prompt(this,"密码应为6位");
           PubUtil.focus(jPasswordFieldPass);
            return false;
        }
        
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PassCheckDialog dialog = new PassCheckDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JPasswordField jPasswordFieldPass;
    // End of variables declaration//GEN-END:variables
}
