/*
 * ParamPanel.java
 *
 * Created on 2014-4-10
 */

package com.goldsign.ecpmcs.ui.panel;

import com.goldsign.csfrm.util.MessageShowUtil;
import com.goldsign.csfrm.util.UIUtil;
import com.goldsign.ecpmcs.service.IParamService;
import com.goldsign.ecpmcs.service.impl.ParamService;
import java.util.List;

/**
 * 参数查询（票卡类型、证件类型）
 * 
 * @author Administrator
 */
public class ParamPanel extends javax.swing.JPanel {

    private IParamService paramService;
    
    /** Creates new form GenIssueRequestPanel */
    public ParamPanel() {
        this.paramService = new ParamService();
        initComponents();
        doQuery();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        rsTabPanel = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        mainSPn = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        mainSPI = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(254, 254, 254));
        setPreferredSize(new java.awt.Dimension(845, 589));

        mainPnl.setBackground(new java.awt.Color(254, 254, 254));
        mainPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPnl.setPreferredSize(new java.awt.Dimension(807, 74));

        rsTabPanel.setBackground(new java.awt.Color(255, 255, 255));
        rsTabPanel.setForeground(new java.awt.Color(94, 55, 16));
        rsTabPanel.setFont(new java.awt.Font("宋体", 1, 15)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));

        mainSPn.setBackground(new java.awt.Color(255, 255, 255));
        mainSPn.setBorder(null);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainSPn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainSPn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        rsTabPanel.addTab("票卡类型", jPanel4);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        mainSPI.setBackground(new java.awt.Color(254, 254, 254));
        mainSPI.setBorder(null);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainSPI, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainSPI, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        rsTabPanel.addTab("证件类型", jPanel2);

        org.jdesktop.layout.GroupLayout mainPnlLayout = new org.jdesktop.layout.GroupLayout(mainPnl);
        mainPnl.setLayout(mainPnlLayout);
        mainPnlLayout.setHorizontalGroup(
            mainPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rsTabPanel)
        );
        mainPnlLayout.setVerticalGroup(
            mainPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPnlLayout.createSequentialGroup()
                .add(rsTabPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 564, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 1, Short.MAX_VALUE))
        );

        rsTabPanel.getAccessibleContext().setAccessibleName("票卡类型");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(mainPnl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mainPnl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JScrollPane mainSPI;
    private javax.swing.JScrollPane mainSPn;
    private javax.swing.JTabbedPane rsTabPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * 查询
     * 
     */
    private void doQuery(){
        //清空提示信息
        MessageShowUtil.infoOpMsg("");
        //查询票卡类型
        List<Object[]> cardType = paramService.getCardType();
        //查询票卡类型
        List<Object[]> identifyType = paramService.getIdentifyType();
        
        int sum = cardType.size() + identifyType.size();
        MessageShowUtil.infoOpMsg("成功查询" + sum + "条记录");
        
        //生成列表
        genCardTypeSetTable(cardType);
        genIdentifyTypeSetTable(identifyType);
    }
    
    /**
     * 根据结果集，生成列表
     * 
     * @param result 
     */
    private void genCardTypeSetTable(List<Object[]> result) {
        //列名称
        String[] columnNames = {"主类型代码", "主类型名称", "子类型代码", "子类型名称"};
        //列宽度
        int[] columnSize = {172, 395, 172, 394};
        
        //生成列表
        UIUtil.genResultSetTable(this.mainSPn, result, columnNames, columnSize);
    }
    
    /**
     * 根据结果集，生成列表
     * 
     * @param result 
     */
    private void genIdentifyTypeSetTable(List<Object[]> result) {
        //列名称
        String[] columnNames = {"代码", "证件名称"};
        //列宽度
        int[] columnSize = {566, 567};
        
        //生成列表
        UIUtil.genResultSetTable(this.mainSPI, result, columnNames, columnSize);
    }
    
}
