grant select, insert, update, delete on w_op_prm_dev_code_acc to w_acc_cm_app;
grant select, insert, update, delete on w_op_prm_dev_code_acc to w_acc_tk_app;
grant select on w_op_prm_dev_code_acc to w_acc_tk_dev;
grant select, insert, update, delete on w_st_list_sign_card to w_acc_cm_app;
grant select, insert, update, delete on w_st_list_sign_card to w_acc_tk_app;
grant select on w_st_list_sign_card to w_acc_tk_dev;
grant select, insert, update, delete on w_op_prm_phy_logic_list to w_acc_cm_app;
grant select, insert, update, delete on w_op_prm_phy_logic_list to w_acc_tk_app;
grant select on w_op_prm_phy_logic_list to w_acc_tk_dev;
grant select, insert, update, delete on w_op_his_phy_logic_list to w_acc_cm_app;
grant select, insert, update, delete on w_op_his_phy_logic_list to w_acc_tk_app;
grant select on w_op_his_phy_logic_list to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_CARD_SUB to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_CARD_SUB to w_acc_tk_app;
grant select on W_OP_PRM_CARD_SUB to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_SYS_OPERATOR to w_acc_cm_app;
grant select, insert, update, delete on W_OP_SYS_OPERATOR to w_acc_tk_app;
grant select on W_OP_SYS_OPERATOR to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_SYS_GROUP_OPERATOR to w_acc_cm_app;
grant select, insert, update, delete on W_OP_SYS_GROUP_OPERATOR to w_acc_tk_app;
grant select on W_OP_SYS_GROUP_OPERATOR to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_STATION to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_STATION to w_acc_tk_app;
grant select on W_OP_PRM_STATION to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_LINE to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_LINE to w_acc_tk_app;
grant select on W_OP_PRM_LINE to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_DEV_CODE to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_DEV_CODE to w_acc_tk_app;
grant select on W_OP_PRM_DEV_CODE to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_FARE_TABLE to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_FARE_TABLE to w_acc_tk_app;
grant select on W_OP_PRM_FARE_TABLE to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_SAM_LIST to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_SAM_LIST to w_acc_tk_app;
grant select on W_OP_PRM_SAM_LIST to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_BLACK_LIST_OCT_SEC to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_BLACK_LIST_OCT_SEC to w_acc_tk_app;
grant select on W_OP_PRM_BLACK_LIST_OCT_SEC to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_BLACK_LIST_OCT to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_BLACK_LIST_OCT to w_acc_tk_app;
grant select on W_OP_PRM_BLACK_LIST_OCT to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_BLACK_LIST_MTR_SEC to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_BLACK_LIST_MTR_SEC to w_acc_tk_app;
grant select on W_OP_PRM_BLACK_LIST_MTR_SEC to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_PRM_BLACK_LIST_MTR to w_acc_cm_app;
grant select, insert, update, delete on W_OP_PRM_BLACK_LIST_MTR to w_acc_tk_app;
grant select on W_OP_PRM_BLACK_LIST_MTR to w_acc_tk_dev;
grant select, insert, update, delete on W_OP_CFG_SYS to w_acc_cm_app;
grant select, insert, update, delete on W_OP_CFG_SYS to w_acc_tk_app;
grant select on W_OP_CFG_SYS to w_acc_tk_dev;
