/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReadCardJPanel.java
 *
 * Created on 2011-7-15, 8:32:26
 */

package com.goldsign.etmcs.ui.panel;

import com.goldsign.csfrm.ui.panel.BasePanel;
import com.goldsign.csfrm.util.MessageShowUtil;
import com.goldsign.csfrm.vo.CallParam;
import com.goldsign.csfrm.vo.CallResult;
import com.goldsign.esmcs.serial.RwDeviceCommu;
import com.goldsign.etmcs.application.Application;
import com.goldsign.etmcs.env.AppConstant;
import com.goldsign.etmcs.exception.CommuException;
import com.goldsign.etmcs.service.IMakeCardService;
import com.goldsign.etmcs.service.IRwDeviceService;
import com.goldsign.etmcs.service.impl.MakeCardService;
import com.goldsign.etmcs.util.CurrentConnectionStatusUtil;
import com.goldsign.etmcs.util.PubUtil;
import com.goldsign.etmcs.vo.AnalyzeVo;
import com.goldsign.etmcs.vo.MakeCardVo;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author david.wang
 */
public class ReadCardPanel extends BasePanel {

    private IRwDeviceService rwDeviceService;
    private IMakeCardService makeCardService;

    @Override
    public CallResult closingEventCallBack(CallParam callParam) {
        return super.closingEventCallBack(callParam);
    }
    
    
    /** Creates new form ReadCardJPanel */
    public ReadCardPanel() {
        initComponents();
        rwDeviceService = ((Application)AppConstant.application).getRwDeviceService();
        makeCardService = new MakeCardService();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlUsedNum = new javax.swing.JLabel();
        certificateIscompany = new javax.swing.JTextField();
        certificateCode = new javax.swing.JTextField();
        certificateIsmetro = new javax.swing.JTextField();
        certificateName = new javax.swing.JTextField();
        certificateType = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        certificateSex = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        certificateDepartment = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        certificatePositions = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        employeeClass = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bIssueStatus = new javax.swing.JTextField();
        cTicketType = new javax.swing.JTextField();
        cPhysicalID = new javax.swing.JTextField();
        bStatus = new javax.swing.JTextField();
        cLogicalID = new javax.swing.JTextField();
        bCharacter = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cIssueDate = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cExpire = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        rfu = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lBalance = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lDeposite = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cLine = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cStationNo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cDateStart = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cDateEnd = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        dtDaliyActive = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        bEffectDay = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cLimitEntryLine = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cLimitEntryStation = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        cLimitExitLine = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        cLimitExitStation = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        cLimitMode = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btCmtReadCard = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(254, 254, 254));
        setPreferredSize(new java.awt.Dimension(845, 589));

        jPanel1.setBackground(new java.awt.Color(237, 247, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(807, 280));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 39, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("持卡类型：");

        jLabel2.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 39, 80));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("单位职工：");

        jLabel3.setBackground(new java.awt.Color(237, 247, 249));
        jLabel3.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 39, 80));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("员工工号：");

        jLabel4.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 39, 80));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("员工姓名：");

        jLabel5.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 39, 80));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("性别：");

        jlUsedNum.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jlUsedNum.setForeground(new java.awt.Color(0, 39, 80));
        jlUsedNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlUsedNum.setText("证件类型：");

        certificateIscompany.setEditable(false);
        certificateIscompany.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        certificateIscompany.setForeground(new java.awt.Color(70, 95, 125));

        certificateCode.setEditable(false);
        certificateCode.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        certificateCode.setForeground(new java.awt.Color(70, 95, 125));
        certificateCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificateCodeActionPerformed(evt);
            }
        });

        certificateIsmetro.setEditable(false);
        certificateIsmetro.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        certificateIsmetro.setForeground(new java.awt.Color(70, 95, 125));

        certificateName.setEditable(false);
        certificateName.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        certificateName.setForeground(new java.awt.Color(70, 95, 125));
        certificateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificateNameActionPerformed(evt);
            }
        });

        certificateType.setEditable(false);
        certificateType.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        certificateType.setForeground(new java.awt.Color(70, 95, 125));
        certificateType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificateTypeActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(185, 227, 241));
        jTextField3.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(94, 55, 16));
        jTextField3.setText("   员工信息");
        jTextField3.setAlignmentX(0.0F);
        jTextField3.setAlignmentY(0.0F);
        jTextField3.setBorder(null);

        certificateSex.setEditable(false);
        certificateSex.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        certificateSex.setForeground(new java.awt.Color(70, 95, 125));

        jLabel6.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 39, 80));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("单位：");

        certificateDepartment.setEditable(false);
        certificateDepartment.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        certificateDepartment.setForeground(new java.awt.Color(70, 95, 125));

        jLabel7.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 39, 80));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("职务：");

        certificatePositions.setEditable(false);
        certificatePositions.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        certificatePositions.setForeground(new java.awt.Color(70, 95, 125));

        jLabel8.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 39, 80));
        jLabel8.setText("员工级别：");

        employeeClass.setBackground(new java.awt.Color(240, 240, 240));
        employeeClass.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        employeeClass.setForeground(new java.awt.Color(70, 95, 125));
        employeeClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeClassActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 802, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(certificateCode, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .add(certificateIscompany)
                            .add(certificateDepartment))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, certificateIsmetro)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, certificateName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, certificatePositions))
                        .add(20, 20, 20)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jlUsedNum)
                                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, certificateType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, certificateSex, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(employeeClass)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(certificateCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(certificateName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(certificateSex, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(2, 2, 2)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(certificateIscompany, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(certificateIsmetro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlUsedNum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(certificateType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(2, 2, 2)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(certificateDepartment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(certificatePositions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(employeeClass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(237, 247, 249));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(807, 219));

        jLabel10.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 39, 80));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("发行状态：");

        jLabel11.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 39, 80));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("票卡类型：");

        jLabel12.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 39, 80));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("票卡物理卡号：");

        jLabel14.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 39, 80));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("票卡状态：");

        jLabel15.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 39, 80));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("票卡逻辑卡号：");

        jLabel16.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 39, 80));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("票卡物理类型：");

        bIssueStatus.setEditable(false);
        bIssueStatus.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        bIssueStatus.setForeground(new java.awt.Color(70, 95, 125));

        cTicketType.setEditable(false);
        cTicketType.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cTicketType.setForeground(new java.awt.Color(70, 95, 125));

        cPhysicalID.setEditable(false);
        cPhysicalID.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cPhysicalID.setForeground(new java.awt.Color(70, 95, 125));

        bStatus.setEditable(false);
        bStatus.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        bStatus.setForeground(new java.awt.Color(70, 95, 125));

        cLogicalID.setEditable(false);
        cLogicalID.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cLogicalID.setForeground(new java.awt.Color(70, 95, 125));

        bCharacter.setEditable(false);
        bCharacter.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        bCharacter.setForeground(new java.awt.Color(70, 95, 125));

        jLabel18.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 39, 80));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("制票日期：");

        cIssueDate.setEditable(false);
        cIssueDate.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cIssueDate.setForeground(new java.awt.Color(70, 95, 125));

        jLabel19.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 39, 80));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("物理有效期：");

        cExpire.setEditable(false);
        cExpire.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cExpire.setForeground(new java.awt.Color(70, 95, 125));

        jLabel20.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 39, 80));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("SAM逻辑卡号：");

        rfu.setEditable(false);
        rfu.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        rfu.setForeground(new java.awt.Color(70, 95, 125));

        jLabel21.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 39, 80));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("余额（分）：");

        lBalance.setEditable(false);
        lBalance.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        lBalance.setForeground(new java.awt.Color(70, 95, 125));

        jLabel22.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 39, 80));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("押金：");

        lDeposite.setEditable(false);
        lDeposite.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        lDeposite.setForeground(new java.awt.Color(70, 95, 125));

        jLabel23.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 39, 80));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("线路：");

        cLine.setEditable(false);
        cLine.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cLine.setForeground(new java.awt.Color(70, 95, 125));

        jLabel24.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 39, 80));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("站点：");

        cStationNo.setEditable(false);
        cStationNo.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cStationNo.setForeground(new java.awt.Color(70, 95, 125));

        jLabel25.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 39, 80));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("有效期开始时间：");

        cDateStart.setEditable(false);
        cDateStart.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cDateStart.setForeground(new java.awt.Color(70, 95, 125));

        jLabel26.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 39, 80));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("有效期结束时间：");

        cDateEnd.setEditable(false);
        cDateEnd.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cDateEnd.setForeground(new java.awt.Color(70, 95, 125));

        jLabel27.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 39, 80));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("逻辑有效期：");

        dtDaliyActive.setEditable(false);
        dtDaliyActive.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        dtDaliyActive.setForeground(new java.awt.Color(70, 95, 125));

        jLabel28.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 39, 80));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("多日票有效天数：");

        bEffectDay.setEditable(false);
        bEffectDay.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        bEffectDay.setForeground(new java.awt.Color(70, 95, 125));

        jLabel29.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 39, 80));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("限制进站线路：");

        cLimitEntryLine.setEditable(false);
        cLimitEntryLine.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cLimitEntryLine.setForeground(new java.awt.Color(70, 95, 125));

        jLabel30.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 39, 80));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("限制进站站点：");

        cLimitEntryStation.setEditable(false);
        cLimitEntryStation.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cLimitEntryStation.setForeground(new java.awt.Color(70, 95, 125));

        jLabel31.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 39, 80));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("限制出站线路：");

        cLimitExitLine.setEditable(false);
        cLimitExitLine.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cLimitExitLine.setForeground(new java.awt.Color(70, 95, 125));

        jLabel32.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 39, 80));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("限制出站站点：");

        cLimitExitStation.setEditable(false);
        cLimitExitStation.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cLimitExitStation.setForeground(new java.awt.Color(70, 95, 125));

        jLabel33.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 39, 80));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText(" 限制模式：");

        cLimitMode.setEditable(false);
        cLimitMode.setFont(new java.awt.Font("宋体", 0, 16)); // NOI18N
        cLimitMode.setForeground(new java.awt.Color(70, 95, 125));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(185, 227, 241));
        jTextField4.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(94, 55, 16));
        jTextField4.setText("   票卡信息");
        jTextField4.setAlignmentX(0.0F);
        jTextField4.setAlignmentY(0.0F);
        jTextField4.setBorder(null);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cPhysicalID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(20, 20, 20)
                                .add(jLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(bCharacter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(bIssueStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(bStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cTicketType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(20, 20, 20)
                                .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cLogicalID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cIssueDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(20, 20, 20)
                                .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cExpire, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(rfu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(20, 20, 20)
                                .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(lBalance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(lDeposite, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(20, 20, 20)
                                .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cLine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cStationNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cDateStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cDateEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(20, 20, 20)
                                .add(jLabel27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(dtDaliyActive, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(bEffectDay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(20, 20, 20)
                                .add(jLabel29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cLimitEntryLine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cLimitEntryStation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(20, 20, 20)
                                .add(jLabel31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cLimitExitLine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cLimitExitStation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(20, 20, 20)
                                .add(jLabel33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(cLimitMode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 802, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(bIssueStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(bStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cTicketType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cLogicalID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cPhysicalID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(bCharacter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cIssueDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cExpire, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(rfu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(lBalance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(lDeposite, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cLine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cStationNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cDateStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cDateEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(dtDaliyActive, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(bEffectDay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cLimitEntryLine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cLimitEntryStation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cLimitExitLine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cLimitExitStation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(cLimitMode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btCmtReadCard.setFont(new java.awt.Font("宋体", 1, 16)); // NOI18N
        btCmtReadCard.setForeground(new java.awt.Color(0, 39, 80));
        btCmtReadCard.setText("读卡");
        btCmtReadCard.setName("btCmtReadCard"); // NOI18N
        btCmtReadCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCmtReadCardActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(254, 254, 254));
        jCheckBox1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 39, 80));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("是否蜂鸣");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(287, 287, 287)
                        .add(btCmtReadCard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(56, 56, 56)
                        .add(jCheckBox1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 378, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btCmtReadCard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCheckBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCmtReadCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCmtReadCardActionPerformed
        //清空提示信息
        MessageShowUtil.infoOpMsg("");
        
        if(!doRead()){
            return;
        }
    }//GEN-LAST:event_btCmtReadCardActionPerformed

    private void certificateCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificateCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificateCodeActionPerformed

    private void certificateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificateNameActionPerformed

    private void certificateTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificateTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificateTypeActionPerformed

    private void employeeClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeClassActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private boolean doRead(){
        
        boolean connectFlag = false;
        connectFlag = CurrentConnectionStatusUtil.isDatabaseConnected();
        if(!connectFlag){//检测数据库连接
            MessageShowUtil.errorOpMsg( "数据库连接连接异常，请联系管理员！");
            MessageShowUtil.alertErrorMsg( "数据库连接连接异常，请联系管理员！");
            return false;
        }
        
        try {
            //检测ES通讯状态
            connectFlag = CurrentConnectionStatusUtil.isEsCommuConnected();
        } catch (CommuException ex) {
            Logger.getLogger(ReadCardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!connectFlag){
            MessageShowUtil.errorOpMsg( "Es通讯SOCKET端口连接异常，请联系管理员！");
            MessageShowUtil.alertErrorMsg( "Es通讯SOCKET端口连接异常，请联系管理员！");
            return false;
        }
        
        
        //检测KMS通讯状态
        connectFlag = CurrentConnectionStatusUtil.isKmsConnected();
        if(!connectFlag){
            MessageShowUtil.errorOpMsg( "加密机连接异常，请联系管理员！");
            MessageShowUtil.alertErrorMsg( "加密机连接异常，请联系管理员！");
            return false;
        }
        //检测读写器状态
        connectFlag = CurrentConnectionStatusUtil.isRwConnected(rwDeviceService);
        if(!connectFlag){
            MessageShowUtil.errorOpMsg( "读写器连接异常，请联系管理员！");
            MessageShowUtil.alertErrorMsg( "读写器连接异常，请联系管理员！");
            return false;
        }
    
        //检测读写器是否放卡
        connectFlag = CurrentConnectionStatusUtil.isCardOnRW(rwDeviceService);
        if(!connectFlag){
            MessageShowUtil.errorOpMsg( "没有检测到任何票卡，请正确放置卡片！");
            MessageShowUtil.alertErrorMsg( "没有检测到任何票卡，请正确放置卡片！");
            return false;
        }
        //判断是否需要蜂鸣
        if(jCheckBox1.isSelected()){
            com.goldsign.rwcommu.connection.RWSerialConnection.MES_PARAM_BEE = AppConstant.RW_BUZZING_TIME_1;
        }
        CallResult callResult = rwDeviceService.analyze();
        if(!callResult.isSuccess()){
            MessageShowUtil.infoOpMsg(callResult.getMsg());
//            MessageShowUtil.alertErrorMsg("没有检测到任何票卡，请正确放置卡片!");
            return false;
        }
        AnalyzeVo analyzeVo = (AnalyzeVo) callResult.getObj();
        bIssueStatus.setText(PubUtil.getMapString(AppConstant.ISSUE_STATUS, analyzeVo.getbIssueStatus()));
        bStatus.setText(PubUtil.getMapString(AppConstant.TICKET_STATUS, analyzeVo.getbStatus()));
        cTicketType.setText(PubUtil.getMapString(AppConstant.TICKET_TYPE, analyzeVo.getcTicketType().substring(0,2)));
        cLogicalID.setText(analyzeVo.getcLogicalID());
        cPhysicalID.setText(analyzeVo.getcPhysicalID());
        bCharacter.setText(PubUtil.getMapString(AppConstant.PHY_CHARACTER, analyzeVo.getbCharacter()));
        cIssueDate.setText(analyzeVo.getcIssueDate());
        cExpire.setText(analyzeVo.getcExpire());
        rfu.setText(analyzeVo.getRfu());
        lBalance.setText(analyzeVo.getlBalance()+"");
        lDeposite.setText(analyzeVo.getlDeposite()+"");
        cLine.setText(PubUtil.getMapString(AppConstant.C_LINE, analyzeVo.getcLine()));
        cStationNo.setText(PubUtil.getMapString(AppConstant.C_STATION_NO, analyzeVo.getcStationNo()));
        cDateStart.setText(analyzeVo.getcDateStart());
        cDateEnd.setText(analyzeVo.getcDateEnd());
        dtDaliyActive.setText(analyzeVo.getDtDaliyActive());
        bEffectDay.setText(analyzeVo.getbEffectDay());
        cLimitEntryLine.setText(PubUtil.getMapString(AppConstant.C_LINE, analyzeVo.getcLimitEntryLine()));
        cLimitEntryStation.setText(PubUtil.getMapString(AppConstant.C_STATION_NO, analyzeVo.getcLimitEntryStation()));
        cLimitExitLine.setText(PubUtil.getMapString(AppConstant.C_LINE, analyzeVo.getcLimitExitLine()));
        cLimitExitStation.setText(PubUtil.getMapString(AppConstant.C_STATION_NO, analyzeVo.getcLimitExitStation()));
        cLimitMode.setText(PubUtil.getMapString(AppConstant.C_LIMIT_MODE, analyzeVo.getcLimitMode()));
        certificateIscompany.setText(PubUtil.getMapString(AppConstant.CERTIFICATE_ISCOMPANY, analyzeVo.getCertificateIscompany()));
        certificateIsmetro.setText(PubUtil.getMapString(AppConstant.CERTIFICATE_ISMETRO, analyzeVo.getCertificateIsmetro()));
        certificateName.setText(analyzeVo.getCertificateName().trim());
        certificateCode.setText(analyzeVo.getCertificateCode().trim());
        certificateType.setText(PubUtil.getMapString(AppConstant.CERTIFICATE_TYPE, analyzeVo.getCertificateType()));
        certificateSex.setText(PubUtil.getMapString(AppConstant.CERTIFICATE_SEX,analyzeVo.getCertificateSex()));
        
        MakeCardVo mvo = new MakeCardVo();
        mvo.setEmployeeId(analyzeVo.getCertificateCode().trim());
        mvo.setLogicId(analyzeVo.getcLogicalID().trim());
        mvo = makeCardService.getMakeCardsByEmployeeId(mvo);
        
        certificateDepartment.setText(mvo.getEmployeeDepartmentTxt());
        certificatePositions.setText(mvo.getEmployeePositionsTxt());
        employeeClass.setText(mvo.getEmployeeClassTxt());
                
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bCharacter;
    private javax.swing.JTextField bEffectDay;
    private javax.swing.JTextField bIssueStatus;
    private javax.swing.JTextField bStatus;
    private javax.swing.JButton btCmtReadCard;
    private javax.swing.JTextField cDateEnd;
    private javax.swing.JTextField cDateStart;
    private javax.swing.JTextField cExpire;
    private javax.swing.JTextField cIssueDate;
    private javax.swing.JTextField cLimitEntryLine;
    private javax.swing.JTextField cLimitEntryStation;
    private javax.swing.JTextField cLimitExitLine;
    private javax.swing.JTextField cLimitExitStation;
    private javax.swing.JTextField cLimitMode;
    private javax.swing.JTextField cLine;
    private javax.swing.JTextField cLogicalID;
    private javax.swing.JTextField cPhysicalID;
    private javax.swing.JTextField cStationNo;
    private javax.swing.JTextField cTicketType;
    private javax.swing.JTextField certificateCode;
    private javax.swing.JTextField certificateDepartment;
    private javax.swing.JTextField certificateIscompany;
    private javax.swing.JTextField certificateIsmetro;
    private javax.swing.JTextField certificateName;
    private javax.swing.JTextField certificatePositions;
    private javax.swing.JTextField certificateSex;
    private javax.swing.JTextField certificateType;
    private javax.swing.JTextField dtDaliyActive;
    private javax.swing.JTextField employeeClass;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jlUsedNum;
    private javax.swing.JTextField lBalance;
    private javax.swing.JTextField lDeposite;
    private javax.swing.JTextField rfu;
    // End of variables declaration//GEN-END:variables

}
