/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2010-6-7, 12:29:38
 */
package com.goldsign.fm.frame;

import com.goldsign.fm.bom.jni.KeyLock;
import com.goldsign.fm.common.AppConstant;
import com.goldsign.fm.common.AppUtil;
import com.goldsign.fm.common.PubUtil;
import com.goldsign.fm.dialog.PassCheckDialog;
import com.goldsign.fm.dialog.PassDialog;
import com.goldsign.fm.vo.PassResult;

import javax.swing.JTree;
import org.apache.log4j.Logger;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    private static Logger logger = Logger.getLogger(MainFrame.class.getName());

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.initApp();

    }

    private void initApp() {
        AppUtil appUtil = new AppUtil();
        try {

            disVisbleDev();//初始隐藏设备状态组件
            this.initPannel();//设置面板及控件的背景色
            appUtil.maxWindow(this);//主页面全屏
            appUtil.addLogo(this.jLabelLogo);//添加LOGO图片
//            appUtil.getInitConfiguration();//获取配置文件的配置
            //显示线网树状图
            appUtil.showLineNet(this.jScrollPaneLineNet, this.jPanelGraph, this.jScrollPane1Data,
                    this.jLabelDataCaption, this.jLabelGraphCaption, this.jScrollPane1Dev);
            //启动当前时间显示线程
            appUtil.startTimeThread(this.jLabelCurrent);
            
            //显示缺省客流图
            this.showInitFlow();
            JTree tree =(JTree)this.jScrollPaneLineNet.getViewport().getView();
            //启动视图刷新线程
            appUtil.startRefrshThread(tree, jPanelGraph,  jScrollPane1Data,  jLabelDataCaption,  jLabelGraphCaption, jScrollPane1Dev);

        } catch (Exception ex) {
            logger.error(ex);
        }
    }
    private void showInitFlow(){

        JTree tree =(JTree)this.jScrollPaneLineNet.getViewport().getView();
        this.disableButtonForHour();
        tree.setSelectionRow(0);
        
    }
    private void initPannel() {
        this.jPanelDataCaption.setBackground(AppConstant.COLOR_SHOW_BACKGROUND);
        this.jPanelData.setBackground(AppConstant.COLOR_SHOW_BACKGROUND);
        this.jScrollPane1Data.getViewport().setBackground(AppConstant.COLOR_SHOW_BACKGROUND);
        this.jScrollPane1Data.setBorder(null);
        this.jPanelGraphCaption.setBackground(AppConstant.COLOR_SHOW_BACKGROUND);
        this.jPanelGraph.setBackground(AppConstant.COLOR_SHOW_BACKGROUND);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogo = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelLineNet = new javax.swing.JPanel();
        jScrollPaneLineNet = new javax.swing.JScrollPane();
        jPanelShow = new javax.swing.JPanel();
        jPanelData = new javax.swing.JPanel();
        jScrollPane1Data = new javax.swing.JScrollPane();
        jScrollPane1Dev = new javax.swing.JScrollPane();
        jPanelGraph = new javax.swing.JPanel();
        jPanelGraphCaption = new javax.swing.JPanel();
        jLabelGraphCaption = new javax.swing.JLabel();
        jPanelDataCaption = new javax.swing.JPanel();
        jLabelDataCaption = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jLabelTime = new javax.swing.JLabel();
        jLabelCurrent = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonMin = new javax.swing.JButton();
        jButtonHour = new javax.swing.JButton();
        jButtonPass = new javax.swing.JButton();
        jButtonDev = new javax.swing.JButton();
        jButtonCard = new javax.swing.JButton();
        jButtonHourLine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);

        jPanelLogo.setBackground(new java.awt.Color(255, 255, 51));
        jPanelLogo.setName("panelLogo"); // NOI18N

        jLabelLogo.setName("jLabelLogo"); // NOI18N

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jPanelLineNet.setBackground(new java.awt.Color(0, 101, 153));

        jScrollPaneLineNet.setBackground(new java.awt.Color(0, 101, 153));

        javax.swing.GroupLayout jPanelLineNetLayout = new javax.swing.GroupLayout(jPanelLineNet);
        jPanelLineNet.setLayout(jPanelLineNetLayout);
        jPanelLineNetLayout.setHorizontalGroup(
            jPanelLineNetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneLineNet, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );
        jPanelLineNetLayout.setVerticalGroup(
            jPanelLineNetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneLineNet, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        jPanelShow.setBackground(new java.awt.Color(255, 255, 255));
        jPanelShow.setPreferredSize(new java.awt.Dimension(1254, 505));

        jPanelData.setBackground(new java.awt.Color(204, 255, 255));

        jScrollPane1Data.setBackground(new java.awt.Color(0, 101, 153));

        jScrollPane1Dev.setBackground(new java.awt.Color(0, 101, 153));
        jScrollPane1Dev.setOpaque(false);
        jScrollPane1Data.setViewportView(jScrollPane1Dev);

        javax.swing.GroupLayout jPanelDataLayout = new javax.swing.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1Data, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jPanelGraph.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanelGraphLayout = new javax.swing.GroupLayout(jPanelGraph);
        jPanelGraph.setLayout(jPanelGraphLayout);
        jPanelGraphLayout.setHorizontalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1254, Short.MAX_VALUE)
        );
        jPanelGraphLayout.setVerticalGroup(
            jPanelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        jPanelGraphCaption.setBackground(new java.awt.Color(0, 101, 153));

        jLabelGraphCaption.setBackground(new java.awt.Color(0, 101, 153));
        jLabelGraphCaption.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabelGraphCaption.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGraphCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelGraphCaptionLayout = new javax.swing.GroupLayout(jPanelGraphCaption);
        jPanelGraphCaption.setLayout(jPanelGraphCaptionLayout);
        jPanelGraphCaptionLayout.setHorizontalGroup(
            jPanelGraphCaptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGraphCaption, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
        );
        jPanelGraphCaptionLayout.setVerticalGroup(
            jPanelGraphCaptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGraphCaption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanelDataCaption.setBackground(new java.awt.Color(0, 101, 153));

        jLabelDataCaption.setBackground(new java.awt.Color(0, 101, 153));
        jLabelDataCaption.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabelDataCaption.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelDataCaptionLayout = new javax.swing.GroupLayout(jPanelDataCaption);
        jPanelDataCaption.setLayout(jPanelDataCaptionLayout);
        jPanelDataCaptionLayout.setHorizontalGroup(
            jPanelDataCaptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDataCaption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
        );
        jPanelDataCaptionLayout.setVerticalGroup(
            jPanelDataCaptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDataCaption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelShowLayout = new javax.swing.GroupLayout(jPanelShow);
        jPanelShow.setLayout(jPanelShowLayout);
        jPanelShowLayout.setHorizontalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGraphCaption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDataCaption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelShowLayout.setVerticalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLayout.createSequentialGroup()
                .addComponent(jPanelDataCaption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanelGraphCaption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenu.setBackground(new java.awt.Color(102, 102, 102));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTime.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTime.setText("当前时间：");

        jLabelCurrent.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabelCurrent.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCurrent.setText("当前时间");

        jButtonExit.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButtonExit.setText("退出系统");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonMin.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButtonMin.setText("5分钟客流");
        jButtonMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinActionPerformed(evt);
            }
        });

        jButtonHour.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButtonHour.setText("小时客流(柱状)");
        jButtonHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHourActionPerformed(evt);
            }
        });

        jButtonPass.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButtonPass.setText("修改密码");
        jButtonPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassActionPerformed(evt);
            }
        });

        jButtonDev.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButtonDev.setText("设备状态");
        jButtonDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevActionPerformed(evt);
            }
        });

        jButtonCard.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButtonCard.setText("票卡类型");
        jButtonCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCardActionPerformed(evt);
            }
        });

        jButtonHourLine.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jButtonHourLine.setText("小时客流(折线)");
        jButtonHourLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHourLineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(jButtonHour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonHourLine, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCard, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDev, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButtonPass, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabelTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonExit, jButtonPass});

        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelCurrent)
                .addComponent(jButtonHour, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonMin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonExit)
                .addComponent(jButtonPass)
                .addComponent(jButtonDev, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonCard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonHourLine, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonExit, jButtonHour, jButtonMin, jButtonPass, jLabelCurrent, jLabelTime});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLineNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(jPanelLineNet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        PassResult checkResult = new PassResult();
        PassCheckDialog dialog = new PassCheckDialog(this,"退出系统",true,checkResult);
        PubUtil util = new PubUtil();
        util.makeContainerInScreenMiddle(dialog);
        dialog.setVisible(true);//弹出退出系统对话框
        if(!checkResult.isIsSuccess())
        return;

        KeyLock kl = new KeyLock();
        kl.disableKeyLock();
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassActionPerformed
        PassDialog dialog=new PassDialog(this,"密码修改",true);
        PubUtil util = new PubUtil();
        util.makeContainerInScreenMiddle(dialog);
        dialog.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPassActionPerformed

    //设备状态监控
    private void jButtonDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevActionPerformed
        disableButtonForDev();
        disVisbleCard();
        visbleDev();
        this.processFlow();
    }//GEN-LAST:event_jButtonDevActionPerformed

    private void jButtonMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinActionPerformed
        disableButtonForMin();
        disVisbleDev();
        disVisbleCard();
        this.processFlow();
    }//GEN-LAST:event_jButtonMinActionPerformed

    private void jButtonHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHourActionPerformed
        disableButtonForHour();
        disVisbleDev();
        disVisbleCard();
        this.processFlow();
    }//GEN-LAST:event_jButtonHourActionPerformed

    //票卡类型客流
    private void jButtonCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCardActionPerformed
        disableButtonForCard();
        disVisbleDev();
        visbleCard();
        this.processFlow();
    }//GEN-LAST:event_jButtonCardActionPerformed

    private void jButtonHourLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHourLineActionPerformed
        // TODO add your handling code here:
        disableButtonForHourLine();
        disVisbleDev();
        disVisbleCard();
        this.processFlow();
    }//GEN-LAST:event_jButtonHourLineActionPerformed
    
    private void processFlow(){
        AppUtil util = new AppUtil();
        JTree tree = (JTree)this.jScrollPaneLineNet.getViewport().getView();
        util.processFlow(tree, jPanelGraph, jScrollPane1Data, jLabelDataCaption, jLabelGraphCaption, jScrollPane1Dev);
        
    }
    
    private void disableButtonForHour(){
        AppConstant.CURRENT_MODE=AppConstant.MODE_SHOW_HOUR;
        this.jButtonHour.setEnabled(false);
        this.jButtonHourLine.setEnabled(true);
        this.jButtonMin.setEnabled(true);
        this.jButtonDev.setEnabled(true);
        this.jButtonCard.setEnabled(true);
        this.jButtonHourLine.updateUI();
        this.jButtonDev.updateUI();
        this.jButtonHour.updateUI();
        this.jButtonMin.updateUI();
        this.jButtonCard.updateUI();
    }
    
    private void disableButtonForHourLine(){
        AppConstant.CURRENT_MODE=AppConstant.MODE_SHOW_HOUR_LINE;
        this.jButtonHourLine.setEnabled(false);
        this.jButtonHour.setEnabled(true);
        this.jButtonMin.setEnabled(true);
        this.jButtonDev.setEnabled(true);
        this.jButtonCard.setEnabled(true);
        this.jButtonDev.updateUI();
        this.jButtonHour.updateUI();
        this.jButtonHourLine.updateUI();
        this.jButtonMin.updateUI();
        this.jButtonCard.updateUI();
    }
    
    private void disableButtonForCard(){
        AppConstant.CURRENT_MODE=AppConstant.MODE_SHOW_CARD_TYPE;
        this.jButtonHour.setEnabled(true);
        this.jButtonHourLine.setEnabled(true);
        this.jButtonMin.setEnabled(true);
        this.jButtonDev.setEnabled(true);
        this.jButtonCard.setEnabled(false);
        this.jButtonDev.updateUI();
        this.jButtonHour.updateUI();
        this.jButtonHourLine.updateUI();
        this.jButtonMin.updateUI();
        this.jButtonCard.updateUI();
    }
    
     private void disableButtonForMin(){
        AppConstant.CURRENT_MODE=AppConstant.MODE_SHOW_MIN;
        this.jButtonHour.setEnabled(true);
        this.jButtonHourLine.setEnabled(true);
        this.jButtonMin.setEnabled(false);
        this.jButtonDev.setEnabled(true);
        this.jButtonCard.setEnabled(true);
        this.jButtonDev.updateUI();
        this.jButtonHour.updateUI();
        this.jButtonHourLine.updateUI();
        this.jButtonMin.updateUI();
        this.jButtonCard.updateUI();
    }
     
    //取消设备状态模式
    private void disVisbleDev(){
        jPanelGraph.setVisible(true);
        jLabelGraphCaption.setVisible(true);
//        jLabelDataCaption.setVisible(true);//启用设备状态标题
        jScrollPane1Dev.setVisible(false);
    }
    
    //使用设备状态模式
    private void visbleDev(){
        jPanelGraph.setVisible(false);
        jLabelGraphCaption.setVisible(false);
//        jLabelDataCaption.setVisible(false);//失效设备状态标题
        jScrollPane1Dev.setVisible(true);
    }
    
    //取消票卡类型模式
    private void disVisbleCard(){
        jPanelGraph.setVisible(true);
        jLabelGraphCaption.setVisible(true);
        jScrollPane1Data.setVisible(true);
    }
    
    //使用票卡类型模式
    private void visbleCard(){
        jPanelGraph.setVisible(true);
        jLabelGraphCaption.setVisible(false);
//        jScrollPane1Data.setVisible(false);
    }
     
    //点击设备状态时更新按钮
    private void disableButtonForDev(){
        AppConstant.CURRENT_MODE=AppConstant.MODE_SHOW_DEV;
        this.jButtonHour.setEnabled(true);
        this.jButtonHourLine.setEnabled(true);
        this.jButtonMin.setEnabled(true);
        this.jButtonCard.setEnabled(true);
        this.jButtonDev.setEnabled(false);
        this.jButtonDev.updateUI();
        this.jButtonHour.updateUI();
        this.jButtonHourLine.updateUI();
        this.jButtonMin.updateUI();
        this.jButtonCard.updateUI();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCard;
    private javax.swing.JButton jButtonDev;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonHour;
    private javax.swing.JButton jButtonHourLine;
    private javax.swing.JButton jButtonMin;
    private javax.swing.JButton jButtonPass;
    private javax.swing.JLabel jLabelCurrent;
    private javax.swing.JLabel jLabelDataCaption;
    private javax.swing.JLabel jLabelGraphCaption;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelDataCaption;
    private javax.swing.JPanel jPanelGraph;
    private javax.swing.JPanel jPanelGraphCaption;
    private javax.swing.JPanel jPanelLineNet;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelShow;
    private javax.swing.JScrollPane jScrollPane1Data;
    private javax.swing.JScrollPane jScrollPane1Dev;
    private javax.swing.JScrollPane jScrollPaneLineNet;
    // End of variables declaration//GEN-END:variables
}
