--功能: 清理票卡生产系统表

--清理ES通讯连接日志表
DELETE FROM ACC_COMMU.CM_EC_CONNECT_LOG;
--清理ES的FTP连接日志表
DELETE FROM ACC_COMMU.CM_EC_FTP_LOG;
--清理ES的日志表
DELETE FROM ACC_COMMU.CM_EC_LOG;
--清理ES的操作日志表
DELETE FROM ACC_COMMU.CM_EC_OPERATOR_LOG;
--清理ES的接收发送日志表
DELETE FROM ACC_COMMU.CM_EC_RECV_SEND_LOG;
--清理ES的审核文件表
DELETE FROM ACC_TK.IC_ES_FILE_AUDIT;
--清理ES的错误文件表
DELETE FROM ACC_TK.IC_ES_FILE_ERROR;
--清理ES的文件通知表
DELETE FROM ACC_TK.IC_ES_INFO_FILE;
--清理ES的生产单数量更改表
DELETE FROM ACC_TK.IC_ES_ORDER_NUM_CHANGE;
--清理ES的生产单重复卡号表
DELETE FROM ACC_TK.IC_ES_PDU_REPEAT_LOGIC;
--清理ES的生产状态表
DELETE FROM ACC_TK.IC_ES_STATUS;

--清理临时表
DELETE ACC_TK.T#IC_PDU_PLAN_ORDER_MAPPING;
DELETE ACC_TK.T#IC_PDU_ORDER_FORM;
DELETE ACC_TK.T#IC_PDU_PRODUCE_BILL_DETAIL;
DELETE acc_tk.T#IC_PDU_RESULT_DETAIL;

--清理库计划单号、出库单号表、生产单表、生产明细表
DELETE ACC_TK.ic_pdu_plan_order_mapping;
DELETE acc_tk.IC_PDU_PRODUCE_BILL;
DELETE ACC_TK.IC_PDU_ORDER_FORM;
DELETE ACC_TK.IC_OUT_DATE_PLAN;
DELETE acc_tk.ic_out_bill_detail;
DELETE ACC_TK.IC_PDU_PRODUCE_BILL_DETAIL;

--清理物理卡号与逻辑卡号对照表、备份表
DELETE ACC_ST.op_his_phy_logic_list;
DELETE ACC_ST.op_prm_phy_logic_list;

--删除生产数据-初始化
DELETE ACC_TK.IC_ES_INITI_INFO;
DELETE ACC_TK.IC_ES_INITI_INFO_BUF;

--删除生产数据-删除预赋值
DELETE ACC_TK.IC_ES_HUNCH_INFO;
DELETE ACC_TK.IC_ES_HUNCH_INFO_BUF;

--删除生产数据-重编码
DELETE ACC_TK.IC_ES_AGAIN_INFO;
DELETE ACC_TK.IC_ES_AGAIN_INFO_BUF;

--删除生产数据-注销
DELETE ACC_TK.IC_ES_LOGOUT_INFO;
DELETE ACC_TK.IC_ES_LOGOUT_INFO_BUF;
  
--提交
commit;