
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GenIssueRequestPanel.java
 *
 * Created on 2011-8-3, 8:31:03
 */

package com.goldsign.sammcs.ui.panel;

import com.goldsign.csfrm.ui.common.JDatePicker;
import com.goldsign.csfrm.util.DateHelper;
import com.goldsign.csfrm.util.ExcelExport;
import com.goldsign.csfrm.util.MessageShowUtil;
import com.goldsign.csfrm.util.UIUtil;
import com.goldsign.csfrm.vo.SelectOptionVo;
import com.goldsign.sammcs.env.AppConstant;
import com.goldsign.sammcs.service.IMakeCardService;
import com.goldsign.sammcs.service.impl.MakeCardService;
import com.goldsign.sammcs.util.CSVFileHandler;
import com.goldsign.sammcs.util.Util;
import com.goldsign.sammcs.vo.MakeCardQueryVo;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JTable;
import org.apache.log4j.Logger;

/**
 * 制卡订单查询
 * 
 * @author Administrator
 */
public class MadeCardQueryPanel extends javax.swing.JPanel {

    private static Logger logger = Logger.getLogger(MadeCardQueryPanel.class.getName());
    
    private JTable resultSetTableMain;
    
    private IMakeCardService makeCardService;
    

    /** Creates new form GenIssueRequestPanel */
    public MadeCardQueryPanel() {
        this.makeCardService = new MakeCardService();
        initComponents();
        initQueryCon();
        //doQuery();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        mainSPn = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        makeCardTimeBeginCb = new javax.swing.JComboBox();
        btQuery = new javax.swing.JButton();
        makeCardTimeEndCb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btExport = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 254, 254));
        setPreferredSize(new java.awt.Dimension(845, 589));

        mainPnl.setBackground(new java.awt.Color(254, 254, 254));
        mainPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPnl.setPreferredSize(new java.awt.Dimension(807, 74));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(185, 227, 241));
        jTextField5.setFont(new java.awt.Font("宋体", 1, 15)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(94, 55, 16));
        jTextField5.setText("   结果列表");
        jTextField5.setAlignmentX(0.0F);
        jTextField5.setAlignmentY(0.0F);
        jTextField5.setBorder(null);

        org.jdesktop.layout.GroupLayout mainPnlLayout = new org.jdesktop.layout.GroupLayout(mainPnl);
        mainPnl.setLayout(mainPnlLayout);
        mainPnlLayout.setHorizontalGroup(
            mainPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPnlLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(mainPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, mainSPn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 788, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 788, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        mainPnlLayout.setVerticalGroup(
            mainPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPnlLayout.createSequentialGroup()
                .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainSPn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(237, 247, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(792, 105));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 39, 80));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("制卡日期：");

        makeCardTimeBeginCb.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        makeCardTimeBeginCb.setForeground(new java.awt.Color(0, 39, 80));
        makeCardTimeBeginCb =new JDatePicker(JDatePicker.STYLE_CN_DATE1);

        btQuery.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btQuery.setForeground(new java.awt.Color(0, 39, 80));
        btQuery.setText("查询");
        btQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQueryActionPerformed(evt);
            }
        });

        makeCardTimeEndCb.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        makeCardTimeEndCb.setForeground(new java.awt.Color(0, 39, 80));
        makeCardTimeEndCb =new JDatePicker(JDatePicker.STYLE_CN_DATE1);

        jLabel4.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 39, 80));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("至：");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(185, 227, 241));
        jTextField3.setFont(new java.awt.Font("宋体", 1, 15)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(94, 55, 16));
        jTextField3.setText("   查询条件");
        jTextField3.setAlignmentX(0.0F);
        jTextField3.setAlignmentY(0.0F);
        jTextField3.setBorder(null);

        btExport.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btExport.setForeground(new java.awt.Color(0, 39, 80));
        btExport.setText("导出");
        btExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 788, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 1, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(49, 49, 49)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(makeCardTimeBeginCb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(makeCardTimeEndCb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btQuery, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btExport, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(makeCardTimeEndCb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btQuery)
                    .add(makeCardTimeBeginCb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btExport))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mainPnl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 792, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 793, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainPnl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 462, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQueryActionPerformed
        doQuery();
    }//GEN-LAST:event_btQueryActionPerformed

    private void btExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportActionPerformed
        doExport();
    }//GEN-LAST:event_btExportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExport;
    private javax.swing.JButton btQuery;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JScrollPane mainSPn;
    private javax.swing.JComboBox makeCardTimeBeginCb;
    private javax.swing.JComboBox makeCardTimeEndCb;
    // End of variables declaration//GEN-END:variables

    /*
     * 导出查询数据
     */
    private void doExport() {
//        CSVFileHandler exp = new CSVFileHandler(resultSetTableMain,this);
//        exp.execute();
        resultSetTableMain.setName("制卡查询");
        JTable[] jTables = {resultSetTableMain};  
        ExcelExport.exportXLSJTableColumnSpread(jTables, this, AppConstant.COLUMN_SIZES);
    }
    
    /**
     * 查询
     * 
     */
    private void doQuery(){
        MakeCardQueryVo queryVo = getQueryVo();
        
        if (null == queryVo.getMakeCardTimeBegin() || "".equals(queryVo.getMakeCardTimeBegin()) 
                || null == queryVo.getMakeCardTimeEnd() || "".equals(queryVo.getMakeCardTimeEnd())) {
            MessageShowUtil.alertInfoMsg( "查询日期不能为空，查询日期段为三个月内！");
            return ;
        }
        if (queryVo.getMakeCardTimeBegin().compareTo(queryVo.getMakeCardTimeEnd())>0) {
            MessageShowUtil.alertInfoMsg( "查询开始日期不能大于结束日期！");
            return ;
        }

        Date beginOpTime = Util.fmtStrToDay(queryVo.getMakeCardTimeBegin());
        Date endOpTime = Util.fmtStrToDay(queryVo.getMakeCardTimeEnd());

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(beginOpTime);
        calendar.add(Calendar.MONTH,3);
        Date after3MonthDay = calendar.getTime();
        if (after3MonthDay.before(endOpTime)) {
            MessageShowUtil.alertInfoMsg("请选择查询日期段为三个月内！");
            return ;
        }
        
        //查询
        List<Object[]> cards = makeCardService.queryIssueDetails(queryVo);
        
        if(cards.size()>0){
            btExport.setEnabled(true);//查询有数据时，导出按键可用
        }
        
        //生成列表
        genMainResultSetTable(cards);
        MessageShowUtil.infoOpMsg( "成功查询"+cards.size()+"条记录！");
    
    }
    
    /**
     * 根据结果集，生成列表
     * 
     * @param result 
     */
    private void genMainResultSetTable(List<Object[]> result) {
        //列名称
        String[] columnNames = AppConstant.COLUMN_NAMES;
        //列宽度
        int[] columnSize = AppConstant.COLUMN_SIZES;
        
        //生成列表
        resultSetTableMain = UIUtil.genResultSetTable(this.mainSPn, result, columnNames, columnSize);
    }

    /**
     * 初始化查询条件
     * 
     */
    private void initQueryCon() {

        btExport.setEnabled(false);

    }
    
    private MakeCardQueryVo getQueryVo() {
        MakeCardQueryVo queryVo = new MakeCardQueryVo();
        queryVo.setMakeCardTimeBegin(DateHelper.str10yyyy_MM_ddToStr8yyyyMMdd(makeCardTimeBeginCb.getSelectedItem().toString()));
        queryVo.setMakeCardTimeEnd(DateHelper.str10yyyy_MM_ddToStr8yyyyMMdd(makeCardTimeEndCb.getSelectedItem().toString()));
        
        
        return queryVo;
        
    }

}
